### ISSUE TITLE
Create Lurk syntax spec

### ISSUE THREAD

**Issue by jpeg07** [lurk-lab/lurk-lisp#61]
Not much to expound on initially. We'd like a good syntax spec by the end of the year, and I think @winston-h-zhang is the point person for it.

**Comment by jpeg07** [comment]
### Conversation moved here from Discord:

@jpeg07 
Just checking if you think you'll have a draft syntax spec completed in the next few weeks. (https://github.com/orgs/lurk-lang/projects/1/views/1). It's on our "roadmap" for the end of this year, and I just want to know if that is an accurate prediction or not.

@johnchandlerburnham 
Yeah, shouldn’t be a problem. @winston-h-zhang has done some preliminary stuff on the language spec, but I’m planning on getting my syntax.rs module finished next week with a working nom parser
Lmk if there are specific things you guys want to see in the spec doc though. I’m planning on mainly focusing on documenting it from the standpoint of allowing other people to write valid parsers/printers, but we could probably standardize erroring too

@winston-h-zhang 
Hey, sorry for the late response, I can definitely take over the lurk syntax spec -- I don't actually have much yet but I'm planning to do a simple BNF description plus some English details -- does that sound good?

@jpeg07 
Let’s move these conversations to the GitHub issue so conversation is more open. Also because it’s the holiday and I will possibly forget these messages starting next week.

**Comment by jpeg07** [comment]
@johnchandlerburnham @winston-h-zhang moving discussion about syntax spec here. 

cc @porcuquine for reference

**Comment by winston-h-zhang** [comment]
Hey, sorry again about the delays. I had final exams this week and was held up on those. The syntax spec will be completed by tomorrow.

**Comment by jpeg07** [comment]
> Hey, sorry again about the delays. I had final exams this week and was held up on those. The syntax spec will be completed by tomorrow.

Great. Let me know when/where this is done. If you make a PR (haven't checked but will), ideally have it close this issue on merge. 🙏

**Comment by jpeg07** [comment]
(Also - I hope your exams went well 😃)

**Comment by huitseeker** [comment]
Closing as obsolete
